services:
  botdiscord:
    container_name: botdiscord
    build: ./Bot-Discord
    image: bot-discord
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_ID_OWNER=${DISCORD_ID_OWNER}
      - REDIS_URL=http://redis:6379
      - URL_FETCH=http://restapi:80
    depends_on:
      - redis

  restapi:
    container_name: restapi
    build: ./Rest-API
    image: rest-api
    environment:
      - DISCORD_ID_OWNER=${DISCORD_ID_OWNER}
      - REDIS_URL=http://redis:6379
      - PORT=80
      - NODE_ENV=production
    depends_on:
      - redis
      - postgres
    ports:
      - "80:80"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${NAME_DATABASE}
      - POSTGRES_USER=${USER_DATABASE}
      - POSTGRES_PASSWORD=${PASSWORD_DATABASE}
    ports:
      - "5432:5432"
