services:
  botDiscord:
    build: ./Bot-Discord
    image: bot-discord
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      
      - REDIS_URL=http://redis:6379

      - HOST_DATABASE=http://postgres:5432
      - USER_DATABASE=${USER_DATABAS}
      - PASSWORD_DATABASE=${PASSWORD_DATABASE}
      - NAME_DATABASE=${NAME_DATABASE}
    depends_on:
      - cache
      - database

  cache:
    image: redis
    ports:
      - "6379:6379"

  database:
    image: postgres
    environment:
      - POSTGRES_DB=${NAME_DATABASE}
      - POSTGRES_USER=${USER_DATABAS}
      - POSTGRES_PASSWORD=${PASSWORD_DATABASE}
    ports:
      - "5432:5432"
